Debugging workflow

diff --git a/.github/workflows/continous-integration-agustin.yml b/.github/workflows/continous-integration-agustin.yml
--- a/.github/workflows/continous-integration-agustin.yml
+++ b/.github/workflows/continous-integration-agustin.yml
@@ -19,5 +19,17 @@ jobs:
           echo "username=${{ secrets.USERNAME }}" >> credentials.ini
           echo "password=${{ secrets.PASSWORD }}" >> credentials.ini
 
+      - name: Verificar existencia del Dockerfile
+        run: |
+          if [ -f Dockerfile ]; then
+            echo "Dockerfile encontrado correctamente."
+          else
+            echo "Error: Dockerfile no encontrado en la raíz del proyecto."
+            exit 1
+          fi
+
+      - name: Mostrar contenido del directorio
+        run: ls -la
+
       - name: Build Docker image
-        run: docker build -t devops_ws . --tag devops_ws_$(date +%s)
+        run: docker build -f Dockerfile -t devops_ws . --tag devops_ws_$(date +%s)
